import Head from 'next/head'
import { useRouter } from 'next/router'
import EventHeader from '../Components/Events/EventHeader'
import Events from '../Components/Events/Events'


export default function Home() {
  
  const router = useRouter();

const handlesearch =(year,month)=>{
  const filterpath = `events/${year}/${month}`
   router.push(filterpath)
}

  return (
    <div >
      <Head>
        <title>Home pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
          
      <EventHeader onSearch={handlesearch} />
      <Events />

      
    </div>
  )
}
