import Head from 'next/head'
import { useRouter } from 'next/router'
import Script from 'next/script';
import EventHeader from '../Components/Events/EventHeader'
import Events from '../Components/Events/Events'
import { useEffect,useState } from 'react';


export default function Home() {
  const [trans,setTrans]=useState(null)
  
  const router = useRouter();

const handlesearch =(year,month)=>{
  const filterpath = `events/${year}/${month}`
   router.push(filterpath)
}

   

  return (
    <div >
      <Head>
        <title>Home pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      <script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element')
}
</script>



      </Head>
       
    <Script type="text/javascript" src="http://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></Script>

<div id="google_translate_element"></div>
        

     
      <EventHeader onSearch={handlesearch} />
      <Events />

      
    
    </div>
  )
}
